### ISSUE TITLE
About username and password

### ISSUE THREAD

**Issue by uMtMu** [eglute/copystack#4]
Hi,
I'm new to openstack. I'm trying to understand your code. 

In auth files(from_auth, to_auth) there are OS_USERNAME and OS_PASSWORD envars. Which user's username and password they are? Keystone? Nova? I used keystone admin password but i didn't work.

**Comment by eglute** [comment]
Hello,
They need to be the same ones as in your openrc file: https://docs.openstack.org/mitaka/install-guide-obs/keystone-openrc.html
The code reads from_auth and to_auth files. If you have SSL (https) enabled, you will also need to provide SSL certificates.

**Comment by uMtMu** [comment]
Okey. I filled like https://docs.openstack.org/mitaka/install-guide-obs/keystone-openrc.html already. I solved my first problem. 

What is OS_AUTH_IP? I couldn't find any thing in google and https://docs.openstack.org/mitaka/install-guide-obs/keystone-openrc.html

**Comment by uMtMu** [comment]
I think there is problem in my devstack understanding. I will read more and return to you.

**Comment by eglute** [comment]
OS_AUTH_IP is keystone's auth URL, but in format http://IP or http://domain. Can also be HTTPS. https://github.com/eglute/copystack/blob/e4f8b36cc06c1c3ad6b81d0403466dfa4931d392/from_auth#L5
